_SCM_HEADER:
GOTO _SCM_SEGMENT2
_RAW_BYTE "s"					// GTASA identifier
_RAW_ARRAY DWORD _VAR_SIZE 0x0	// VAR space

_SCM_SEGMENT2:
_RAW_BYTE 1						// segment ID
_RAW_DWORD _NUM_MODELS
_STRING_ARRAY 24 _NUM_MODELS _MODEL_NAMES
GOTO _SCM_SEGMENT3

_SCM_SEGMENT3:
GOTO _SCM_SEGMENT4